name: Actions Workflow
on: 
  #push:
  #schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  pull_request:
    #types: [closed,assigned, opened, reopened]
  repository_dispatch:
    types: [RunTest]
 
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: |
          echo ${{ github.event.client_payload.id}} 
          echo ${{ github.event.client_payload.key}} 

      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: check out
        uses: actions/Checkout@v1
      - name: List files after
        run: |
          pwd
          ls -a
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: John
      - name: Log Greaating time
        run: echo "${{ steps.greet.outputs.time}}" 
