name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@Version v1
        with:
          who-to-greet: John
      - name: Log Greaating time
        run: echo "${{ steps.greet.outputs.time}}" 
